
# FILENAME: .github/workflows/ci.yml
name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # ENVIRONMENT SETUP
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # DEPENDENCY CACHING
    - name: Cache Gradle dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

    # LINTING STAGE
    - name: Configure Checkstyle
      run: |
        mkdir -p config/checkstyle
        curl -sL https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml > config/checkstyle/checkstyle.xml
      # COMMENT: Auto-configured Checkstyle since no linter present

    - name: Run Linter (Checkstyle)
      run: ./gradlew checkstyleMain
      # QUALITY GATE: Fails on style violations if any are found.  Assuming a `checkstyleMain` task exists in Gradle build file.

    # BUILD STAGE
    - name: Build project
      run: ./gradlew clean build
      # QUALITY GATE: Fails on compilation errors. Supports multi-module builds because Gradle handles this automatically.

    # TEST STAGE
    - name: Run tests
      run: ./gradlew test
      # QUALITY GATE: Fails on test failures.
